#
# Use Manorrock Server
#
FROM manorrock/server:arm-v20.6.0

#
# Setup for cross-platform building.
#
RUN ["cross-build-start"]

#
# Copy Manorrock Munchkin into Tomcat 9.
#
COPY target/munchkin.war /usr/local/tomcat/webapps/ROOT.war

#
# End cross platform building.
#
RUN ["cross-build-end"]
